FROM node:16-alpine

ENV NODE_ENV=Dev

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --production
RUN npm install moleculer-repl

COPY . .

CMD ["npm", "run", "dev"]
